api_platform:
    title: 'Remind Me REST API'
    description: 'API to manage the Remind-me app'
    version: '1.0.0'
    
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        exists_parameter_name: 'exists'
        order: 'ASC'
        order_parameter_name: 'order'
        pagination: 
            enabled: false
            items_per_page: 5