nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['.']
        allow_methods: []
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^\/api\/list':
            origin_regex: true
            allow_headers: ['authorization', 'content-type','access-control-allow-origin']
            allow_methods: ['POST', 'PATCH', 'OPTIONS', 'GET', 'DELETE']
            max_age: 3600

        '^\/api\/login_check':
            origin_regex: true
            allow_headers: ['authorization', 'content-type','access-control-allow-origin']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600

        '^\/api\/users':
            origin_regex: true
            allow_headers: ['authorization', 'content-type','access-control-allow-origin']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600

        '^\/api':
            origin_regex: true
            allow_headers: ['Content-Type','access-control-allow-origin']
            allow_methods: ['OPTIONS', 'GET']
            max_age: 3600
